// This file is generated by Slice Machine. Update with care!

import LandingPageTitle from './LandingPageTitle';

export {
	LandingPageTitle,
};

export const components = {
	landing_page_title: LandingPageTitle,
};
